---
# The image is needed so that every Gitpod Workspace comes with gitpod/workspace-full-vnc whenever they start it.
image:
  file: .gitpod.Dockerfile

# Now, there are specific tasks for dependencies, servers, noVNC, ports and even pre-builds so that you start without delay.
tasks:
  - before: echo "Initialising Dependency install"
    name: Deps for Tauri
    init: touch /tmp/.applock
    command: |
        sudo apt update && sudo apt install -y libwebkit2gtk-4.0-dev \
          build-essential \
          curl \
          wget \
          libssl-dev \
          libgtk-3-dev \
          libappindicator3-dev \
          patchelf \
          librsvg2-dev
    
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash

        nvm install node --latest-npm
        nvm use node
        rustc --version
        rm /tmp/.applock

  - name: Yarn App Server
    init: sleep 1 && while [ -f /tmp/.applock ]; do sleep 1; done
    command: |
          yarn
          yarn dev
  - name: Yarn Docs Server
    init: echo "Starting docs server"
    command: |
          cd docs
          yarn
          yarn start
  

vscode:
  extensions:
    - kimlimjustin.jsdoc-generator
    
    - esbenp.prettier-vscode

    - orta.vscode-jest
  
# Ports config
ports:
  - port: 3000
    onOpen: open-preview
  - port: 6080
    onOpen: open-browser
  - port: 5900
    onOpen: ignore

# GitHub Prebuilds
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
# enable for all branches in this repo (defaults to false)
    branches: true
# enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
# enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
# add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: true
# add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
