blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/kimlimjustin/xplorer/discussions/new
    about: Got a question? Instead of asking it here, ask it over at GitHub Discussions